### PR TITLE
fix loop index

### PR DESCRIPTION
**Pull request by Albertbol**

### CODE REVIEW

**Comment by Albertbol** [comment]
Hey, 
The great package I like is the lookup API idea for AppStore.
But I get an undefined index error, I believe its because of this or am I mixing up something?
Thanks

**Comment by kauemurakami** [comment]
Good @Albertbol  evening, could you send me details of your code snippet? because in the last version it was fixed.
This <= must remain for a reason -> If the appstore version is the same as your app it will return that there is an update, and we don't want that.
If it is EQUAL or MINOR, there are no updates.
Remembering that even if your v1 is 1.0.0+000 and in the appstore it is 1.0.0+001 it will recover this new version.

**Comment by kauemurakami** [comment]
sorry you're right, the for condition is wrong, I'll accept the merge.

**Comment by Albertbol** [comment]
Thank you very much! Great work and package.

**Pull request merged**
