### PR TITLE
models + cleaner code

### PR DESCRIPTION
**Pull request by pom11**
- added AppVersionData to models
- cleaner fetch_version.dart and app_version_update.dart

### CODE REVIEW

**Comment by kauemurakami** [comment]
thanks !! I'm sorry I didn't upgrade the version this weekend.
Tomorrow I will take some time for this, your changes need to be published! tks <3

**Comment by pom11** [comment]
no worries. i m using the repo via git directly. 

pls retest the code with diff versions. tested with xxx.xxx.xxx+xxx

**Comment by kauemurakami** [comment]
Very good !!! I'm here now testing to upload the new version!
Thanks a lot for your support, it's my first open source and I'm really enjoying the contributions.

I'm in difficult times, but I'll always make time to stop by! gratitude

**Comment by kauemurakami** [comment]
Is ready

**Comment by pom11** [comment]
awesome! 

will take a look into supporting more platforms

**Pull request merged**
