### PR TITLE
packages update

### PR DESCRIPTION
**Pull request by Macacoazul01**

### CODE REVIEW

**Comment by kauemurakami** [comment]
i go review and resolve conflicts, thanks for your contribuition.

**Comment by Macacoazul01** [comment]
@kauemurakami when are you planning to release a new version?

**Comment by romatallinn** [comment]
@Macacoazul01 @kauemurakami not a maintainer here, but a few comments.

- Can somebody add `.flutter-plugins` and `.flutter-plugins-dependencies` to `.gitignore`? These are locally generated files, so shouldn't be staged.
- `package_info_plus` is now available at `v7.0.0`; maybe bump it here once again to make it up-to-date?

Looking forward to an update.

**Comment by Macacoazul01** [comment]
Gonna update later tonight

**Comment by kauemurakami** [comment]
In the Previous PR I had a problem when reproducing here, you can test the main, Your PR also has conflicts to be corrected, perhaps you can add the modifications with the updated main to avoid this conflict, and if you can reproduce it I can publish it, if Otherwise I'm very tight with a new version of the app at the company I work for, as soon as I'm done there, I'll correct it here, as I'm facing the same problem with the info plus package in the app 
```dart
* What went wrong:
Execution failed for task ':device_info_plus:compileDebugJavaWithJavac'.
> error: invalid source release: 17
```
@Macacoazul01

**Comment by kauemurakami** [comment]
I fix this with update AS

**Pull request closed without merging**
